name: daily_grace_devotional
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  intl: ^0.19.0
  http: ^0.13.3
  image_picker: ^1.1.1
  url_launcher: ^6.0.9
  omni_datetime_picker: ^1.1.0
  email_validator: ^2.1.17
  flutter_local_notifications: ^9.5.3
  timezone: ^0.8.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  # flutter_quill: ^9.3.21
  # image_picker: ^0.8.9
  # provider: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/thumbnails/
    - assets/
    - .env
  uses-material-design: true
