name: note_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  youtube_player_flutter: ^9.0.1
  image_picker: ^1.1.1
  firebase_storage: ^11.7.4
  omni_datetime_picker: ^1.1.0
  email_validator: ^2.1.17
  # googleapis: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/thumbnails/
  uses-material-design: true
